# Generated by Django 5.1 on 2024-08-17 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review_clients',
            options={'ordering': ('sort',), 'verbose_name_plural': 'Clients'},
        ),
    ]
