# Generated by Django 5.1 on 2024-08-17 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_review_clients_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='review_clients',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
