# Generated by Django 5.1 on 2024-08-17 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_review_clients_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review_clients',
            name='photo',
            field=models.ImageField(default=None, upload_to='home_photos'),
        ),
    ]
