# Generated by Django 5.1 on 2024-08-17 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_review_clients_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review_clients',
            name='photo',
            field=models.ImageField(upload_to='home_photo'),
        ),
    ]
