# Generated by Django 5.1 on 2024-08-17 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_review_clients_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review_clients',
            options={'ordering': ('sort',), 'verbose_name_plural': 'Client'},
        ),
    ]
