# Generated by Django 5.1 on 2024-08-17 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_review_clients_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review_clients',
            old_name='name_client',
            new_name='name',
        ),
    ]
