# Generated by Django 5.1 on 2024-08-17 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_rename_name_client_review_clients_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review_clients',
            options={'ordering': ('sort',), 'verbose_name_plural': 'Clients'},
        ),
    ]
