# Generated by Django 5.1 on 2024-08-17 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_review_clients_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review_clients',
            options={'ordering': ('sort',), 'verbose_name_plural': 'Client'},
        ),
        migrations.AlterField(
            model_name='review_clients',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='home_photos'),
        ),
    ]
