# Generated by Django 5.1 on 2024-08-17 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_category_options_alter_dish_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dish',
            options={'ordering': ('sort',), 'verbose_name_plural': 'Dish'},
        ),
    ]
