# Generated by Django 5.1 on 2024-08-14 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chefs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chefs_information',
            options={'ordering': ('sort',), 'verbose_name_plural': 'Staff'},
        ),
        migrations.RemoveField(
            model_name='chefs_information',
            name='age',
        ),
        migrations.RemoveField(
            model_name='chefs_information',
            name='description',
        ),
        migrations.AddField(
            model_name='chefs_information',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='chefs_information',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='chefs_information',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='chefs_information',
            name='photo',
            field=models.ImageField(default=None, upload_to='staff_photos'),
        ),
        migrations.AddField(
            model_name='chefs_information',
            name='position',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='chefs_information',
            name='sort',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chefs_information',
            name='twitter',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='chefs_information',
            name='name',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
