# Generated by Django 5.1 on 2024-08-14 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='information_contact',
            options={'verbose_name': 'Contact Info', 'verbose_name_plural': 'Contacts'},
        ),
        migrations.RemoveField(
            model_name='information_contact',
            name='name',
        ),
        migrations.RemoveField(
            model_name='information_contact',
            name='number',
        ),
        migrations.AddField(
            model_name='information_contact',
            name='address',
            field=models.TextField(default='NewYork'),
        ),
        migrations.AddField(
            model_name='information_contact',
            name='email',
            field=models.EmailField(default='None', max_length=254),
        ),
        migrations.AddField(
            model_name='information_contact',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='information_contact',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='information_contact',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='information_contact',
            name='phone',
            field=models.CharField(default='1234567890', max_length=255),
        ),
        migrations.AddField(
            model_name='information_contact',
            name='twitter',
            field=models.URLField(blank=True),
        ),
    ]
